name: note_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  # state management
  provider: ^6.1.5

  # database
  supabase_flutter: ^2.9.1
  sqflite: ^2.4.2

  # core dependencies
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  get_it: ^8.0.3  # dependency ingestion
  go_router: ^15.2.4
  connectivity_plus: ^6.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
